# Generated by Django 6.0.6 on 2026-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.URLField(blank=True, max_length=500, verbose_name='封面图片URL'),
        ),
    ]
