# Generated by Django 6.0.6 on 2026-07-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_post_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系列名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='系列描述')),
            ],
            options={
                'verbose_name': '文章系列',
                'verbose_name_plural': '文章系列',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='series_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='系列序号'),
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.series', verbose_name='所属系列'),
        ),
    ]
