# Generated by Django 6.0.6 on 2026-07-14 03:28

from django.db import migrations
from django.utils.text import slugify


def populate_authors(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Category = apps.get_model('blog', 'Category')
    Tag = apps.get_model('blog', 'Tag')
    Series = apps.get_model('blog', 'Series')
    Memo = apps.get_model('blog', 'Memo')
    Post = apps.get_model('blog', 'Post')

    try:
        owner = User.objects.filter(is_superuser=True).order_by('id').first()
    except Exception:
        owner = None

    if not owner:
        return

    # Category
    for obj in Category.objects.filter(author__isnull=True):
        obj.author = owner
        obj.save(update_fields=['author'])

    # Tag
    for obj in Tag.objects.filter(author__isnull=True):
        obj.author = owner
        obj.save(update_fields=['author'])

    # Series
    for obj in Series.objects.filter(author__isnull=True):
        obj.author = owner
        obj.save(update_fields=['author'])

    # Memo
    for obj in Memo.objects.filter(author__isnull=True):
        obj.author = owner
        obj.save(update_fields=['author'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_invitecode_userprofile_category_author_memo_author_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_authors, noop),
    ]
