# Generated by Django 6.0.6 on 2026-07-16 10:54

import blog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_make_authors_non_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '公开发表'), ('private', '私密')], default='published', max_length=10, verbose_name='文章状态'),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=blog.models.upload_image_path, verbose_name='图片文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('md5_hash', models.CharField(max_length=32, unique=True, verbose_name='MD5哈希')),
                ('sha1_hash', models.CharField(max_length=40, verbose_name='SHA1哈希')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(bytes)')),
                ('width', models.PositiveSmallIntegerField(verbose_name='宽度(px)')),
                ('height', models.PositiveSmallIntegerField(verbose_name='高度(px)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
                'ordering': ['-created_time'],
            },
        ),
    ]
