# Generated by Django 6.0.6 on 2026-07-16 15:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=blog.models.avatar_upload_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='头像URL(旧)'),
        ),
    ]
