# Generated by Django 6.0.6 on 2026-07-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userprofile_avatar_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64, verbose_name='浏览器指纹哈希')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='IP哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'indexes': [models.Index(fields=['post', 'fingerprint_hash', 'ip_hash', 'created_at'], name='idx_viewlog_lookup')],
            },
        ),
    ]
