# Generated by Django 6.0.6 on 2026-07-18 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL, verbose_name='封禁执行人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_reason',
            field=models.TextField(blank=True, verbose_name='封禁原因'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='是否封禁'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_permanent_ban',
            field=models.BooleanField(default=False, help_text='永久封禁不受递归解封影响，只能直接取消', verbose_name='永久封禁'),
        ),
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='申诉内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_appeals', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申诉用户')),
            ],
            options={
                'verbose_name': '封禁申诉',
                'verbose_name_plural': '封禁申诉',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('user',), name='unique_pending_appeal_per_user')],
            },
        ),
    ]
