# Generated by Django 6.0.6 on 2026-07-18 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userprofile_banned_at_userprofile_banned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-modified_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__3983fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_status_9be002_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status', '-modified_time'], name='blog_post_author__14c94a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-modified_time'], name='blog_post_status_9689cf_idx'),
        ),
    ]
