# Generated by Django 6.0.6 on 2026-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='license',
            field=models.CharField(choices=[('CC BY-NC 4.0', 'CC BY-NC 4.0（署名-非商业性使用）'), ('CC BY 4.0', 'CC BY 4.0（署名）'), ('CC BY-SA 4.0', 'CC BY-SA 4.0（署名-相同方式共享）'), ('CC BY-NC-SA 4.0', 'CC BY-NC-SA 4.0（署名-非商业-相同方式共享）'), ('CC BY-ND 4.0', 'CC BY-ND 4.0（署名-禁止演绎）'), ('CC BY-NC-ND 4.0', 'CC BY-NC-ND 4.0（署名-非商业-禁止演绎）'), ('CC0', 'CC0（公共领域）')], default='CC BY-NC 4.0', max_length=30, verbose_name='许可协议'),
        ),
    ]
