# Generated by Django 6.0.6 on 2026-07-21 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_notification'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='游客邮箱'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='游客昵称'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='可见'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['guest_email', 'is_visible'], name='blog_commen_guest_e_817d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_visible'], name='blog_commen_is_visi_ba10a2_idx'),
        ),
    ]
