# Generated by Django 6.0.6 on 2026-09-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_guest_and_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='令牌名称')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='令牌哈希')),
                ('prefix', models.CharField(editable=False, max_length=16, verbose_name='令牌前缀')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'API 令牌',
                'verbose_name_plural': 'API 令牌',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='blog_apitok_token_h_d3436f_idx'), models.Index(fields=['user', 'revoked_at'], name='blog_apitok_user_id_dd8248_idx')],
            },
        ),
    ]
